const purpose =
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui faucibus ac amet, scelerisque ultricies nunc pellentesque eget tempor. Sit mi ornare nisl senectus. Aenean nunc condimentum sit bibendum mi. Eu magna adipiscing odiom...';

export const mockDaos = [
  {
    id: '1',
    name: 'DAO name 1',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
  {
    id: '2',
    name: 'DAO name 2',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
  {
    id: '3',
    name: 'DAO name 3',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
  {
    id: '4',
    name: 'DAO name 4',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
  {
    id: '5',
    name: 'DAO name 5',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
  {
    id: '6',
    name: 'DAO name 6',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
  {
    id: '7',
    name: 'DAO name 7',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
  {
    id: '8',
    name: 'DAO name 8',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
  {
    id: '9',
    name: 'DAO name 9',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
  {
    id: '10',
    name: 'DAO name 10',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
];
