import { Proposal, ProposalStatus } from 'types/proposal';
import { Dao } from '../../types/dao';

const purpose =
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui faucibus ac amet, scelerisque ultricies nunc pellentesque eget tempor. Sit mi ornare nisl senectus. Aenean nunc condimentum sit bibendum mi. Eu magna adipiscing odiom...';

export const mockDaos: Dao[] = [
  {
    id: '1',
    name: 'DAO name 1',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
    members: ['member1', 'member2', 'member3'],
    network: 'test.network',
    votePeriod: new Date('Mon May 17 2021 22:11:10 GMT+0300'),
  },
  {
    id: '2',
    name: 'DAO name 2',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
    members: ['member1', 'member2', 'member3'],
    network: 'test.network',
    votePeriod: new Date('Mon May 17 2021 22:11:10 GMT+0300'),
  },
  {
    id: '3',
    name: 'DAO name 3',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
    members: ['member1', 'member2', 'member3'],
    network: 'test.network',
    votePeriod: new Date('Mon May 17 2021 22:11:10 GMT+0300'),
  },
  {
    id: '4',
    name: 'DAO name 4',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
    members: ['member1', 'member2', 'member3'],
    network: 'test.network',
    votePeriod: new Date('Mon May 17 2021 22:11:10 GMT+0300'),
  },
  {
    id: '5',
    name: 'DAO name 5',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
    members: ['member1', 'member2', 'member3'],
    network: 'test.network',
    votePeriod: new Date('Mon May 17 2021 22:11:10 GMT+0300'),
  },
  {
    id: '6',
    name: 'DAO name 6',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
    members: ['member1', 'member2', 'member3'],
    network: 'test.network',
    votePeriod: new Date('Mon May 17 2021 22:11:10 GMT+0300'),
  },
  {
    id: '7',
    name: 'DAO name 7',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
    members: ['member1', 'member2', 'member3'],
    network: 'test.network',
    votePeriod: new Date('Mon May 17 2021 22:11:10 GMT+0300'),
  },
  {
    id: '8',
    name: 'DAO name 8',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
    members: ['member1', 'member2', 'member3'],
    network: 'test.network',
    votePeriod: new Date('Mon May 17 2021 22:11:10 GMT+0300'),
  },
  {
    id: '9',
    name: 'DAO name 9',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
    members: ['member1', 'member2', 'member3'],
    network: 'test.network',
    votePeriod: new Date('Mon May 17 2021 22:11:10 GMT+0300'),
  },
  {
    id: '10',
    name: 'DAO name 10',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
    members: ['member1', 'member2', 'member3'],
    network: 'test.network',
    votePeriod: new Date('Mon May 17 2021 22:11:10 GMT+0300'),
  },
  {
    id: '11',
    name: 'DAO name 1',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
    members: ['member1', 'member2', 'member3'],
    network: 'test.network',
    votePeriod: new Date('Mon May 17 2021 22:11:10 GMT+0300'),
  },
  {
    id: '12',
    name: 'DAO name 2',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
    members: ['member1', 'member2', 'member3'],
    network: 'test.network',
    votePeriod: new Date('Mon May 17 2021 22:11:10 GMT+0300'),
  },
  {
    id: '13',
    name: 'DAO name 3',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
    members: ['member1', 'member2', 'member3'],
    network: 'test.network',
    votePeriod: new Date('Mon May 17 2021 22:11:10 GMT+0300'),
  },
  {
    id: '14',
    name: 'DAO name 4',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
    members: ['member1', 'member2', 'member3'],
    network: 'test.network',
    votePeriod: new Date('Mon May 17 2021 22:11:10 GMT+0300'),
  },
  {
    id: '15',
    name: 'DAO name 5',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
    members: ['member1', 'member2', 'member3'],
    network: 'test.network',
    votePeriod: new Date('Mon May 17 2021 22:11:10 GMT+0300'),
  },
  {
    id: '16',
    name: 'DAO name 6',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
    members: ['member1', 'member2', 'member3'],
    network: 'test.network',
    votePeriod: new Date('Mon May 17 2021 22:11:10 GMT+0300'),
  },
  {
    id: '17',
    name: 'DAO name 7',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
    members: ['member1', 'member2', 'member3'],
    network: 'test.network',
    votePeriod: new Date('Mon May 17 2021 22:11:10 GMT+0300'),
  },
  {
    id: '18',
    name: 'DAO name 8',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
    members: ['member1', 'member2', 'member3'],
    network: 'test.network',
    votePeriod: new Date('Mon May 17 2021 22:11:10 GMT+0300'),
  },
  {
    id: '19',
    name: 'DAO name 9',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
    members: ['member1', 'member2', 'member3'],
    network: 'test.network',
    votePeriod: new Date('Mon May 17 2021 22:11:10 GMT+0300'),
  },
  {
    id: '20',
    name: 'DAO name 10',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
    members: ['member1', 'member2', 'member3'],
    network: 'test.network',
    votePeriod: new Date('Mon May 17 2021 22:11:10 GMT+0300'),
  },
];

export const proposals: Array<Proposal> = [
  {
    id: '1',
    name: 'New Council Member',
    daoName: 'daoName',
    status: ProposalStatus.Delayed,
    target: ' targetname.near',
    about:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui faucibus ac amet, scelerisque ultricies nunc pellentesque eget tempor. Sit mi ornare nisl senectus. Aenean nunc condimentum sit bibendum mi. Eu magna adipiscing odiom...',
    payout: 1,
    proposer: 'veryverylongcouncilname_1.near',
    approveCount: 29000,
    rejectCount: 13,
  },
  {
    id: '2',
    name: 'New Council Member',
    daoName: 'daoName',
    status: ProposalStatus.Approved,
    target: ' targetname.near',
    about:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui faucibus ac amet, scelerisque ultricies nunc pellentesque eget tempor. Sit mi ornare nisl senectus. Aenean nunc condimentum sit bibendum mi. Eu magna adipiscing odiom...',
    payout: 1,
    proposer: 'veryverylongcouncilname_1.near',
    approveCount: 29000,
    rejectCount: 13,
  },
  {
    id: '3',
    name: 'New Council Member',
    daoName: 'daoName',
    status: ProposalStatus.Delayed,
    target: ' targetname.near',
    about:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui faucibus ac amet, scelerisque ultricies nunc pellentesque eget tempor. Sit mi ornare nisl senectus. Aenean nunc condimentum sit bibendum mi. Eu magna adipiscing odiom...',
    payout: 1,
    proposer: 'veryverylongcouncilname_1.near',
    approveCount: 29000,
    rejectCount: 13,
  },
  {
    id: '4',
    name: 'New Council Member',
    daoName: 'daoName',
    status: ProposalStatus.Rejected,
    target: ' targetname.near',
    about:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui faucibus ac amet, scelerisque ultricies nunc pellentesque eget tempor. Sit mi ornare nisl senectus. Aenean nunc condimentum sit bibendum mi. Eu magna adipiscing odiom...',
    payout: 1,
    proposer: 'veryverylongcouncilname_1.near',
    approveCount: 29000,
    rejectCount: 13,
  },
  {
    id: '5',
    name: 'New Council Member',
    daoName: 'daoName',
    status: ProposalStatus.InProgress,
    target: ' targetname.near',
    about:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui faucibus ac amet, scelerisque ultricies nunc pellentesque eget tempor. Sit mi ornare nisl senectus. Aenean nunc condimentum sit bibendum mi. Eu magna adipiscing odiom...',
    payout: 1,
    proposer: 'veryverylongcouncilname_1.near',
    approveCount: 29000,
    rejectCount: 13,
  },
  {
    id: '6',
    name: 'New Council Member',
    daoName: 'daoName',
    status: ProposalStatus.Delayed,
    target: ' targetname.near',
    about:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui faucibus ac amet, scelerisque ultricies nunc pellentesque eget tempor. Sit mi ornare nisl senectus. Aenean nunc condimentum sit bibendum mi. Eu magna adipiscing odiom...',
    payout: 1,
    proposer: 'veryverylongcouncilname_1.near',
    approveCount: 29000,
    rejectCount: 13,
  },
  {
    id: '7',
    name: 'New Council Member',
    daoName: 'daoName',
    status: ProposalStatus.Approved,
    target: ' targetname.near',
    about:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui faucibus ac amet, scelerisque ultricies nunc pellentesque eget tempor. Sit mi ornare nisl senectus. Aenean nunc condimentum sit bibendum mi. Eu magna adipiscing odiom...',
    payout: 1,
    proposer: 'veryverylongcouncilname_1.near',
    approveCount: 29000,
    rejectCount: 13,
  },
  {
    id: '8',
    name: 'New Council Member',
    daoName: 'daoName',
    status: ProposalStatus.Approved,
    target: ' targetname.near',
    about:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui faucibus ac amet, scelerisque ultricies nunc pellentesque eget tempor. Sit mi ornare nisl senectus. Aenean nunc condimentum sit bibendum mi. Eu magna adipiscing odiom...',
    payout: 1,
    proposer: 'veryverylongcouncilname_1.near',
    approveCount: 29000,
    rejectCount: 13,
  },
  {
    id: '9',
    name: 'New Council Member',
    daoName: 'daoName',
    status: ProposalStatus.Delayed,
    target: ' targetname.near',
    about:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui faucibus ac amet, scelerisque ultricies nunc pellentesque eget tempor. Sit mi ornare nisl senectus. Aenean nunc condimentum sit bibendum mi. Eu magna adipiscing odiom...',
    payout: 1,
    proposer: 'veryverylongcouncilname_1.near',
    approveCount: 29000,
    rejectCount: 13,
  },
  {
    id: '10',
    name: 'New Council Member',
    daoName: 'daoName',
    status: ProposalStatus.InProgress,
    target: ' targetname.near',
    about:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui faucibus ac amet, scelerisque ultricies nunc pellentesque eget tempor. Sit mi ornare nisl senectus. Aenean nunc condimentum sit bibendum mi. Eu magna adipiscing odiom...',
    payout: 1,
    proposer: 'veryverylongcouncilname_1.near',
    approveCount: 29000,
    rejectCount: 13,
  },
  {
    id: '11',
    name: 'New Council Member',
    daoName: 'daoName',
    status: ProposalStatus.Rejected,
    target: ' targetname.near',
    about:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui faucibus ac amet, scelerisque ultricies nunc pellentesque eget tempor. Sit mi ornare nisl senectus. Aenean nunc condimentum sit bibendum mi. Eu magna adipiscing odiom...',
    payout: 1,
    proposer: 'veryverylongcouncilname_1.near',
    approveCount: 29000,
    rejectCount: 13,
  },
  {
    id: '12',
    name: 'New Council Member',
    daoName: 'daoName',
    status: ProposalStatus.Delayed,
    target: ' targetname.near',
    about:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui faucibus ac amet, scelerisque ultricies nunc pellentesque eget tempor. Sit mi ornare nisl senectus. Aenean nunc condimentum sit bibendum mi. Eu magna adipiscing odiom...',
    payout: 1,
    proposer: 'veryverylongcouncilname_1.near',
    approveCount: 29000,
    rejectCount: 13,
  },
];
