import { Proposal, ProposalStatus } from 'types/proposal';

const purpose =
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui faucibus ac amet, scelerisque ultricies nunc pellentesque eget tempor. Sit mi ornare nisl senectus. Aenean nunc condimentum sit bibendum mi. Eu magna adipiscing odiom...';

export const mockDaos = [
  {
    id: '1',
    name: 'DAO name 1',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
  {
    id: '2',
    name: 'DAO name 2',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
  {
    id: '3',
    name: 'DAO name 3',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
  {
    id: '4',
    name: 'DAO name 4',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
  {
    id: '5',
    name: 'DAO name 5',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
  {
    id: '6',
    name: 'DAO name 6',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
  {
    id: '7',
    name: 'DAO name 7',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
  {
    id: '8',
    name: 'DAO name 8',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
  {
    id: '9',
    name: 'DAO name 9',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
  {
    id: '10',
    name: 'DAO name 10',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
  {
    id: '11',
    name: 'DAO name 1',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
  {
    id: '12',
    name: 'DAO name 2',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
  {
    id: '13',
    name: 'DAO name 3',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
  {
    id: '14',
    name: 'DAO name 4',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
  {
    id: '15',
    name: 'DAO name 5',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
  {
    id: '16',
    name: 'DAO name 6',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
  {
    id: '17',
    name: 'DAO name 7',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
  {
    id: '18',
    name: 'DAO name 8',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
  {
    id: '19',
    name: 'DAO name 9',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
  {
    id: '20',
    name: 'DAO name 10',
    purpose,
    numberOfProposals: 3,
    bond: 5,
    amountMembers: 57,
    daoFunds: 123,
    image: 'https://reactjs.org/logo-og.png',
  },
];

export const proposals: Array<Proposal> = [
  {
    id: '1',
    name: 'New Council Member',
    daoName: 'daoName',
    status: ProposalStatus.Delayed,
    target: ' targetname.near',
    about:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui faucibus ac amet, scelerisque ultricies nunc pellentesque eget tempor. Sit mi ornare nisl senectus. Aenean nunc condimentum sit bibendum mi. Eu magna adipiscing odiom...',
    payout: 1,
    proposer: 'veryverylongcouncilname_1.near',
    approveCount: 29000,
    rejectCount: 13,
  },
  {
    id: '2',
    name: 'New Council Member',
    daoName: 'daoName',
    status: ProposalStatus.Approved,
    target: ' targetname.near',
    about:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui faucibus ac amet, scelerisque ultricies nunc pellentesque eget tempor. Sit mi ornare nisl senectus. Aenean nunc condimentum sit bibendum mi. Eu magna adipiscing odiom...',
    payout: 1,
    proposer: 'veryverylongcouncilname_1.near',
    approveCount: 29000,
    rejectCount: 13,
  },
  {
    id: '3',
    name: 'New Council Member',
    daoName: 'daoName',
    status: ProposalStatus.Delayed,
    target: ' targetname.near',
    about:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui faucibus ac amet, scelerisque ultricies nunc pellentesque eget tempor. Sit mi ornare nisl senectus. Aenean nunc condimentum sit bibendum mi. Eu magna adipiscing odiom...',
    payout: 1,
    proposer: 'veryverylongcouncilname_1.near',
    approveCount: 29000,
    rejectCount: 13,
  },
  {
    id: '4',
    name: 'New Council Member',
    daoName: 'daoName',
    status: ProposalStatus.Rejected,
    target: ' targetname.near',
    about:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui faucibus ac amet, scelerisque ultricies nunc pellentesque eget tempor. Sit mi ornare nisl senectus. Aenean nunc condimentum sit bibendum mi. Eu magna adipiscing odiom...',
    payout: 1,
    proposer: 'veryverylongcouncilname_1.near',
    approveCount: 29000,
    rejectCount: 13,
  },
  {
    id: '5',
    name: 'New Council Member',
    daoName: 'daoName',
    status: ProposalStatus.InProgress,
    target: ' targetname.near',
    about:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui faucibus ac amet, scelerisque ultricies nunc pellentesque eget tempor. Sit mi ornare nisl senectus. Aenean nunc condimentum sit bibendum mi. Eu magna adipiscing odiom...',
    payout: 1,
    proposer: 'veryverylongcouncilname_1.near',
    approveCount: 29000,
    rejectCount: 13,
  },
  {
    id: '6',
    name: 'New Council Member',
    daoName: 'daoName',
    status: ProposalStatus.Delayed,
    target: ' targetname.near',
    about:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui faucibus ac amet, scelerisque ultricies nunc pellentesque eget tempor. Sit mi ornare nisl senectus. Aenean nunc condimentum sit bibendum mi. Eu magna adipiscing odiom...',
    payout: 1,
    proposer: 'veryverylongcouncilname_1.near',
    approveCount: 29000,
    rejectCount: 13,
  },
  {
    id: '7',
    name: 'New Council Member',
    daoName: 'daoName',
    status: ProposalStatus.Approved,
    target: ' targetname.near',
    about:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui faucibus ac amet, scelerisque ultricies nunc pellentesque eget tempor. Sit mi ornare nisl senectus. Aenean nunc condimentum sit bibendum mi. Eu magna adipiscing odiom...',
    payout: 1,
    proposer: 'veryverylongcouncilname_1.near',
    approveCount: 29000,
    rejectCount: 13,
  },
  {
    id: '8',
    name: 'New Council Member',
    daoName: 'daoName',
    status: ProposalStatus.Approved,
    target: ' targetname.near',
    about:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui faucibus ac amet, scelerisque ultricies nunc pellentesque eget tempor. Sit mi ornare nisl senectus. Aenean nunc condimentum sit bibendum mi. Eu magna adipiscing odiom...',
    payout: 1,
    proposer: 'veryverylongcouncilname_1.near',
    approveCount: 29000,
    rejectCount: 13,
  },
  {
    id: '9',
    name: 'New Council Member',
    daoName: 'daoName',
    status: ProposalStatus.Delayed,
    target: ' targetname.near',
    about:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui faucibus ac amet, scelerisque ultricies nunc pellentesque eget tempor. Sit mi ornare nisl senectus. Aenean nunc condimentum sit bibendum mi. Eu magna adipiscing odiom...',
    payout: 1,
    proposer: 'veryverylongcouncilname_1.near',
    approveCount: 29000,
    rejectCount: 13,
  },
  {
    id: '10',
    name: 'New Council Member',
    daoName: 'daoName',
    status: ProposalStatus.InProgress,
    target: ' targetname.near',
    about:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui faucibus ac amet, scelerisque ultricies nunc pellentesque eget tempor. Sit mi ornare nisl senectus. Aenean nunc condimentum sit bibendum mi. Eu magna adipiscing odiom...',
    payout: 1,
    proposer: 'veryverylongcouncilname_1.near',
    approveCount: 29000,
    rejectCount: 13,
  },
  {
    id: '11',
    name: 'New Council Member',
    daoName: 'daoName',
    status: ProposalStatus.Rejected,
    target: ' targetname.near',
    about:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui faucibus ac amet, scelerisque ultricies nunc pellentesque eget tempor. Sit mi ornare nisl senectus. Aenean nunc condimentum sit bibendum mi. Eu magna adipiscing odiom...',
    payout: 1,
    proposer: 'veryverylongcouncilname_1.near',
    approveCount: 29000,
    rejectCount: 13,
  },
  {
    id: '12',
    name: 'New Council Member',
    daoName: 'daoName',
    status: ProposalStatus.Delayed,
    target: ' targetname.near',
    about:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui faucibus ac amet, scelerisque ultricies nunc pellentesque eget tempor. Sit mi ornare nisl senectus. Aenean nunc condimentum sit bibendum mi. Eu magna adipiscing odiom...',
    payout: 1,
    proposer: 'veryverylongcouncilname_1.near',
    approveCount: 29000,
    rejectCount: 13,
  },
];
